# Generated by Django 4.2.30 on 2026-04-26 18:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_id_alter_productsize_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='occurred_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Amalga oshgan vaqt'),
        ),
        migrations.CreateModel(
            name='DebtRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_fio', models.CharField(max_length=255, verbose_name='Qarz olgan FIO')),
                ('phone', models.CharField(max_length=13, verbose_name='Telefon raqam (+998...)')),
                ('quantity', models.PositiveIntegerField(verbose_name='Dona')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Bir dona narxi')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Jami qarz summasi')),
                ('volume_m3', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Hajm (m³)')),
                ('occurred_at', models.DateTimeField(verbose_name='Qarz olingan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Qarz yozuvi',
                'verbose_name_plural': 'Qarz yozuvlari',
                'ordering': ['-occurred_at'],
            },
        ),
    ]
