# Generated by Django 4.2.30 on 2026-04-26 18:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventorytransaction_occurred_at_debtrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='occurred_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kelib tushgan vaqt'),
        ),
    ]
